"""ML-06 contract and manifest builders."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping

import pandas as pd

from ml_06_fb_io import read_json, utc_now_iso
from ml_06_fb_specs import TARGET_RECENCY_COLUMNS, RatioTransformSpec, ratio_transform_spec


CONTRACT_VARIANTS: tuple[str, ...] = ("original", "log1p", "clip_p9999")
DEFAULT_APPROVE_VARIANT = "clip_p9999"
ML06_POLICY_COLUMNS: tuple[str, ...] = (
    "ml_06_policy",
    "ml_06_ratio_base_column",
    "ml_06_ratio_variant",
    "recency_sentinel_policy",
)
STRICT_BOOL_VALUES = {"TRUE", "FALSE"}


@dataclass(frozen=True)
class ContractValidationResult:
    """Validated ML-06 contract summary."""

    total_rows: int
    selected_count: int
    selected_columns: list[str]
    ratio_base_columns: list[str]


def _contract_columns_with_ml06_policy(columns: list[str]) -> list[str]:
    return list(dict.fromkeys([*columns, *ML06_POLICY_COLUMNS]))


def _cell_text(row: pd.Series, column: str) -> str:
    if column not in row.index or pd.isna(row[column]):
        return ""
    return str(row[column]).strip()


def _strict_bool_series(series: pd.Series, column_name: str) -> pd.Series:
    if series.isna().any():
        rows = (series[series.isna()].index + 2).tolist()
        raise ValueError(f"{column_name} contains missing values. csv_rows={rows[:30]}")
    values = series.astype(str).str.strip()
    invalid = values[~values.isin(STRICT_BOOL_VALUES)]
    if not invalid.empty:
        rows = (invalid.index + 2).tolist()
        raise ValueError(
            f"{column_name} contains unsupported values. "
            f"allowed_values={sorted(STRICT_BOOL_VALUES)}, "
            f"invalid_values={sorted(invalid.unique().tolist())[:30]}, csv_rows={rows[:30]}"
        )
    return values


def _selected_columns(table: pd.DataFrame) -> list[str]:
    if "column_name" not in table.columns or "used_in_ml" not in table.columns:
        raise ValueError("contract must contain column_name and used_in_ml columns")
    used_in_ml = _strict_bool_series(table["used_in_ml"], "used_in_ml")
    selected = table.loc[used_in_ml == "TRUE", "column_name"].astype(str).str.strip().tolist()
    blank = [index + 2 for index, column in zip(table.index, table["column_name"].astype(str).str.strip()) if not column]
    if blank:
        raise ValueError(f"contract contains blank column_name. csv_rows={blank[:30]}")
    duplicated = sorted({column for column in table["column_name"].astype(str).str.strip().tolist() if table["column_name"].astype(str).str.strip().tolist().count(column) > 1})
    if duplicated:
        raise ValueError(f"duplicated contract column_name values: {duplicated[:30]}")
    selected_duplicated = sorted({column for column in selected if selected.count(column) > 1})
    if selected_duplicated:
        raise ValueError(f"duplicated selected feature columns: {selected_duplicated[:30]}")
    if not selected:
        raise ValueError("contract has no selected feature columns")
    return selected


def _empty_contract_row(
    columns: list[str],
    *,
    column_name: str,
    feature_group: str,
    artifact_prefix: str,
    source_column: str,
    ratio_variant: str,
) -> dict[str, Any]:
    row = {column: "" for column in columns}
    values = {
        "contract_version": "ml_06_ratio_transform_v1",
        "artifact_prefix": artifact_prefix,
        "column_name": column_name,
        "used_in_ml": "FALSE",
        "source_column": source_column,
        "column_origin": "ml_06_feature_build",
        "encoding": "passthrough",
        "build_action": "build",
        "build_in_fb": "TRUE",
        "xgb_feature_type": "q",
        "feature_group": feature_group,
        "dtype": "float32",
        "leakage_risk": "low",
        "review_status": "approved",
        "selection_note": "generated by ML-06 ratio transform policy",
        "contract_row_origin": "ml_06_generated",
        "feature_spec_name": "ratio_transform",
        "materialized": "TRUE",
        "observed_dtype": "float32",
        "note": "pure ratio transform; train-only clipping for clip variant",
        "ml_06_policy": "ratio_transform",
        "ml_06_ratio_base_column": source_column,
        "ml_06_ratio_variant": ratio_variant,
    }
    for key, value in values.items():
        if key in row:
            row[key] = value
    return row


def _replace_base_ratios(
    feature_columns: list[str],
    ratio_specs: list[RatioTransformSpec],
    *,
    variant: str,
) -> set[str]:
    selected = set(feature_columns)
    if variant == "original":
        return selected

    replacements = {spec.base_column: spec.log1p_column if variant == "log1p" else spec.clip_column for spec in ratio_specs}
    output: set[str] = set()
    for column in feature_columns:
        output.add(replacements.get(column, column))
    return output


def build_contract_variants(
    source_contract: pd.DataFrame,
    *,
    feature_columns: list[str],
    ratio_specs: list[RatioTransformSpec],
    artifact_prefix: str = "ml_06__r00",
    parent_artifact_prefix: str = "ml_05__r00",
) -> dict[str, pd.DataFrame]:
    """Build original/log1p/clip contracts from the ML-05 approval contract."""

    if "column_name" not in source_contract.columns or "used_in_ml" not in source_contract.columns:
        raise ValueError("source contract must contain column_name and used_in_ml columns")

    columns = _contract_columns_with_ml06_policy(list(source_contract.columns))
    generated_columns: list[str] = []
    for spec in ratio_specs:
        generated_columns.extend([spec.log1p_column, spec.clip_column])

    existing = set(source_contract["column_name"].astype(str).tolist())
    generated_rows: list[dict[str, Any]] = []
    for spec in ratio_specs:
        for column, variant in ((spec.log1p_column, "log1p"), (spec.clip_column, "clip_p9999")):
            if column in existing:
                continue
            generated_rows.append(
                _empty_contract_row(
                    columns,
                    column_name=column,
                    feature_group="ratio_transform",
                    artifact_prefix=artifact_prefix,
                    source_column=spec.base_column,
                    ratio_variant=variant,
                )
            )

    base = pd.concat([source_contract.copy(), pd.DataFrame(generated_rows)], ignore_index=True)
    for column in columns:
        if column not in base.columns:
            base[column] = ""
    base = base[columns].copy()
    base = base.fillna("")
    if "artifact_prefix" in base.columns:
        base["artifact_prefix"] = artifact_prefix
    if "parent_artifact_prefix" in base.columns:
        base["parent_artifact_prefix"] = parent_artifact_prefix
    ratio_base_set = {spec.base_column for spec in ratio_specs}
    for index, row in base.iterrows():
        column = _cell_text(row, "column_name")
        if column in ratio_base_set and not _cell_text(row, "ml_06_policy"):
            base.at[index, "ml_06_policy"] = "ratio_base_source"
            base.at[index, "ml_06_ratio_base_column"] = column
            base.at[index, "ml_06_ratio_variant"] = "original"
        if column in TARGET_RECENCY_COLUMNS:
            base.at[index, "recency_sentinel_policy"] = "minus1_to_zero"
            if not _cell_text(base.loc[index], "ml_06_policy"):
                base.at[index, "ml_06_policy"] = "recency_sentinel"

    variants: dict[str, pd.DataFrame] = {}
    for variant in CONTRACT_VARIANTS:
        selected = _replace_base_ratios(feature_columns, ratio_specs, variant=variant)
        table = base.copy()
        table["used_in_ml"] = table["column_name"].astype(str).map(lambda column: "TRUE" if column in selected else "FALSE")
        variants[variant] = table
    return variants


def build_input_contract(
    source_contract: pd.DataFrame,
    *,
    feature_columns: list[str],
    available_columns: list[str],
    artifact_prefix: str = "ml_06__r00",
    parent_artifact_prefix: str = "ml_05__r00",
    approve_variant: str = DEFAULT_APPROVE_VARIANT,
) -> pd.DataFrame:
    """Create the ML-06 fb_inputs contract from the ML-05 approved contract."""

    if approve_variant not in CONTRACT_VARIANTS:
        raise ValueError(f"unsupported approve_variant: {approve_variant!r}")
    available = set(str(column) for column in available_columns)
    ratio_specs = [
        ratio_transform_spec(column)
        for column in feature_columns
        if column in available and "ratio" in column and "log1p" not in column and "clip" not in column and "hist_lt2_flag" not in column
    ]
    variants = build_contract_variants(
        source_contract,
        feature_columns=feature_columns,
        ratio_specs=ratio_specs,
        artifact_prefix=artifact_prefix,
        parent_artifact_prefix=parent_artifact_prefix,
    )
    contract = variants[approve_variant].copy()
    validate_input_contract(contract, artifact_prefix=artifact_prefix, available_columns=available_columns)
    return contract


def selected_feature_columns(contract: pd.DataFrame) -> list[str]:
    """Return selected ML feature columns from a contract table."""

    return _selected_columns(contract)


def source_feature_columns_for_variants(contract: pd.DataFrame) -> list[str]:
    """Return selected columns with ML-06 ratio variants mapped back to their base columns."""

    selected = _selected_columns(contract)
    if "ml_06_ratio_base_column" not in contract.columns:
        return selected
    by_column = {
        str(row["column_name"]).strip(): _cell_text(row, "ml_06_ratio_base_column")
        for _, row in contract.iterrows()
    }
    return list(dict.fromkeys(by_column.get(column) or column for column in selected))


def ratio_base_columns_from_contract(contract: pd.DataFrame, available_columns: list[str]) -> list[str]:
    """Return ratio base columns required to materialize ML-06 generated ratio features."""

    bases: list[str] = []
    if "ml_06_ratio_base_column" in contract.columns:
        for _, row in contract.iterrows():
            base_column = _cell_text(row, "ml_06_ratio_base_column")
            if base_column:
                bases.append(base_column)
    return list(dict.fromkeys(bases))


def update_contract_materialization(contract: pd.DataFrame, frame: pd.DataFrame) -> pd.DataFrame:
    """Update materialization/dtype metadata without changing selection."""

    table = contract.copy()
    for column in ("materialized", "observed_dtype", "dtype"):
        if column not in table.columns:
            table[column] = ""
        table[column] = table[column].astype("object")
    available = set(frame.columns)
    for index, row in table.iterrows():
        column = _cell_text(row, "column_name")
        if column in available:
            dtype = str(frame[column].dtype)
            table.at[index, "materialized"] = "TRUE"
            table.at[index, "observed_dtype"] = dtype
            table.at[index, "dtype"] = dtype
    selected_missing = sorted(set(_selected_columns(table)) - available)
    if selected_missing:
        raise ValueError(f"selected contract columns are missing from ML-06 output frame: {selected_missing[:30]}")
    return table


def validate_input_contract(
    contract: pd.DataFrame,
    *,
    artifact_prefix: str,
    available_columns: list[str] | None = None,
) -> ContractValidationResult:
    """Validate the ML-06 fb_inputs contract."""

    required = {"column_name", "used_in_ml", "artifact_prefix"}
    missing = required - set(contract.columns)
    if missing:
        raise ValueError(f"ML-06 input contract is missing columns: {sorted(missing)}")
    mismatched = contract[contract["artifact_prefix"].astype(str).str.strip() != artifact_prefix]
    if not mismatched.empty:
        rows = (mismatched.index + 2).tolist()
        raise ValueError(f"artifact_prefix mismatch. expected={artifact_prefix!r}, csv_rows={rows[:30]}")

    selected = _selected_columns(contract)
    ratio_bases = ratio_base_columns_from_contract(contract, available_columns or [])
    if available_columns is not None:
        available = set(str(column) for column in available_columns)
        ratio_variant = contract.get("ml_06_ratio_variant", pd.Series("", index=contract.index)).astype(str).str.strip()
        generated_columns = set(
            contract.loc[ratio_variant.isin({"log1p", "clip_p9999"}), "column_name"].astype(str).str.strip()
        )
        missing_selected = sorted(column for column in selected if column not in available and column not in generated_columns)
        if missing_selected:
            raise ValueError(f"selected non-generated columns are missing from input parquet: {missing_selected[:30]}")
        missing_bases = sorted(set(ratio_bases) - available)
        if missing_bases:
            raise ValueError(f"ratio base columns are missing from input parquet: {missing_bases[:30]}")
    return ContractValidationResult(
        total_rows=int(len(contract)),
        selected_count=int(len(selected)),
        selected_columns=selected,
        ratio_base_columns=ratio_bases,
    )


def _extract_feature_types(payload: Any, *, source_label: str) -> dict[str, str]:
    """Return the inner feature type map from ML feature type artifacts."""

    if not isinstance(payload, dict):
        raise ValueError(f"feature type payload must be a JSON object: {source_label}")

    raw_feature_types = payload.get("feature_types", payload)
    if not isinstance(raw_feature_types, dict):
        raise ValueError(f"feature_types must be a JSON object: {source_label}")

    feature_types: dict[str, str] = {}
    for column, feature_type in raw_feature_types.items():
        if not isinstance(feature_type, str):
            raise ValueError(
                "feature_types values must be strings. "
                f"source={source_label}, column={column!r}, value_type={type(feature_type).__name__}"
            )
        normalized_type = feature_type.strip()
        if not normalized_type:
            raise ValueError(f"feature type is blank: source={source_label}, column={column!r}")
        feature_types[str(column)] = normalized_type
    return feature_types


def _extend_feature_types(feature_types: Mapping[str, str], generated_columns: list[str]) -> dict[str, str]:
    """Add ML-06 generated ratio columns as quantitative features."""

    extended = {str(column): str(feature_type) for column, feature_type in feature_types.items()}
    for column in generated_columns:
        existing_type = extended.get(column)
        if existing_type is not None and existing_type != "q":
            raise ValueError(
                "generated ratio column already exists with a non-numeric feature type. "
                f"column={column!r}, feature_type={existing_type!r}"
            )
        extended[column] = "q"
    return extended


def build_feature_types(
    *,
    source_feature_types_path: str | Path | None,
    generated_columns: list[str],
) -> dict[str, Any]:
    """Extend ML-05 feature types with ML-06 generated numeric columns."""

    feature_types: dict[str, str] = {}
    if source_feature_types_path is not None:
        payload = read_json(source_feature_types_path)
        feature_types = _extract_feature_types(payload, source_label=str(source_feature_types_path))
    return {"feature_types": _extend_feature_types(feature_types, generated_columns)}


def _dedupe_strings(values: list[str] | tuple[str, ...]) -> list[str]:
    return list(dict.fromkeys(str(value) for value in values))


def _extend_encoding_specs(
    source_specs: Any,
    generated_columns: list[str],
    *,
    selected_columns: list[str] | None = None,
) -> list[dict[str, Any]]:
    """Keep source encoding specs and add passthrough specs for ML-06 generated columns."""

    if source_specs is None:
        specs: list[dict[str, Any]] = []
    elif isinstance(source_specs, list):
        specs = []
        for index, spec in enumerate(source_specs):
            if not isinstance(spec, dict):
                raise ValueError(f"encoding_specs entries must be JSON objects: index={index}")
            specs.append(dict(spec))
    else:
        raise ValueError(f"encoding_specs must be a list when present: type={type(source_specs).__name__}")

    selected = set(selected_columns or [])
    existing_outputs = {
        str(spec.get("output_column", spec.get("source_column", "")))
        for spec in specs
        if spec.get("output_column", spec.get("source_column", "")) != ""
    }
    if selected_columns is not None:
        for spec in specs:
            output_column = str(spec.get("output_column", spec.get("source_column", "")))
            if output_column:
                spec["used_in_ml"] = output_column in selected
    for column in generated_columns:
        if column in existing_outputs:
            continue
        specs.append(
            {
                "source_column": column,
                "output_column": column,
                "encoding": "passthrough",
                "used_in_ml": column in selected if selected_columns is not None else True,
                "build_action": "build",
                "xgb_feature_type": "q",
            }
        )
        existing_outputs.add(column)
    return specs


def _build_manifest_outputs(output_paths: Mapping[str, Path]) -> dict[str, str]:
    required_keys = (
        "ml_all",
        "ml_train",
        "ml_val",
        "ml_test",
        "contract_approve",
        "contract_original",
        "contract_log1p",
        "contract_clip",
        "feature_types",
        "encoding_manifest",
    )
    missing = [key for key in required_keys if key not in output_paths]
    if missing:
        raise ValueError(f"ML-06 output path mapping is missing required keys: {missing}")

    return {
        "all_path": str(output_paths["ml_all"]),
        "train_path": str(output_paths["ml_train"]),
        "val_path": str(output_paths["ml_val"]),
        "test_path": str(output_paths["ml_test"]),
        "feature_contract_path": str(output_paths["contract_approve"]),
        "contract_original_path": str(output_paths["contract_original"]),
        "contract_log1p_path": str(output_paths["contract_log1p"]),
        "contract_clip_p9999_path": str(output_paths["contract_clip"]),
        "feature_types_path": str(output_paths["feature_types"]),
        "encoding_manifest_path": str(output_paths["encoding_manifest"]),
    }


def build_encoding_manifest(
    *,
    input_path: Path,
    source_contract_path: Path,
    feature_columns_path: Path,
    source_encoding_manifest_path: Path | None,
    ratio_manifest: Mapping[str, Any],
    generated_columns: list[str],
    row_counts: Mapping[str, int],
    artifact_prefix: str = "ml_06__r00",
    output_dir: Path | None = None,
    output_paths: Mapping[str, Path] | None = None,
    feature_columns: list[str] | None = None,
    materialized_columns: list[str] | None = None,
) -> dict[str, Any]:
    """Extend the ML-05 encoding manifest without breaking training input contracts."""

    if source_encoding_manifest_path is None:
        raise ValueError("source_encoding_manifest_path is required to preserve ML training input metadata")

    source_manifest = read_json(source_encoding_manifest_path)
    if not isinstance(source_manifest, dict):
        raise ValueError(f"source encoding manifest must be a JSON object: {source_encoding_manifest_path}")

    feature_types = _extend_feature_types(
        _extract_feature_types(source_manifest, source_label=str(source_encoding_manifest_path)),
        generated_columns,
    )
    category_values = source_manifest.get("category_values", {})
    if category_values is None:
        category_values = {}
    if not isinstance(category_values, dict):
        raise ValueError(f"encoding manifest category_values must be a JSON object: {source_encoding_manifest_path}")

    source_feature_columns = source_manifest.get("feature_columns", [])
    if feature_columns is None:
        if not isinstance(source_feature_columns, list):
            raise ValueError(f"encoding manifest feature_columns must be a list: {source_encoding_manifest_path}")
        feature_columns = [str(column) for column in source_feature_columns]
    manifest_feature_columns = _dedupe_strings(feature_columns)

    source_materialized_columns = source_manifest.get("materialized_columns", [])
    if materialized_columns is None:
        if not isinstance(source_materialized_columns, list):
            raise ValueError(f"encoding manifest materialized_columns must be a list: {source_encoding_manifest_path}")
        materialized_columns = [str(column) for column in source_materialized_columns]
    manifest_materialized_columns = _dedupe_strings(materialized_columns)

    encoding_specs = _extend_encoding_specs(
        source_manifest.get("encoding_specs", []),
        generated_columns,
        selected_columns=manifest_feature_columns,
    )
    manifest_outputs = _build_manifest_outputs(output_paths) if output_paths is not None else source_manifest.get("outputs", {})
    if not isinstance(manifest_outputs, dict):
        raise ValueError(f"encoding manifest outputs must be a JSON object: {source_encoding_manifest_path}")

    created_at_utc = utc_now_iso()
    build_metadata = {
        "created_at_utc": created_at_utc,
        "experiment_id": "ML-06",
        "run_id": "r00",
        "artifact_prefix": artifact_prefix,
        "input_path": str(input_path),
        "source_contract_path": str(source_contract_path),
        "feature_columns_path": str(feature_columns_path),
        "source_encoding_manifest_path": str(source_encoding_manifest_path),
        "recency_policy": "target two account recency columns: -1 sentinel converted to 0; first flags preserved",
        "ratio_policy": ratio_manifest.get("skip_policy"),
        "ratio_quantile": ratio_manifest.get("ratio_quantile"),
        "generated_columns": generated_columns,
        "generated_column_count": len(generated_columns),
        "row_counts": dict(row_counts),
        "contract_variants": list(CONTRACT_VARIANTS),
    }

    if output_dir is not None:
        build_metadata["output_dir"] = str(output_dir)

    manifest = dict(source_manifest)
    manifest.update(
        {
            **build_metadata,
            "artifact_prefix": artifact_prefix,
            "parent_artifact_prefix": source_manifest.get("artifact_prefix"),
            "input": str(input_path),
            "output_dir": str(output_dir) if output_dir is not None else source_manifest.get("output_dir"),
            "outputs": manifest_outputs,
            "feature_columns": manifest_feature_columns,
            "materialized_columns": manifest_materialized_columns,
            "encoding_specs": encoding_specs,
            "feature_types": feature_types,
            "category_values": category_values,
        }
    )
    manifest["ml_06_build"] = build_metadata
    return manifest
